### ISSUE TITLE
Help me! 

### ISSUE THREAD

**Issue by GulmirzaNorboyev** [reactivedroid/TvFlix#15]
**I don't understand the 3rd function of DiffUtil.ItemCallBack well...
<img width="1143" alt="payload" src="https://user-images.githubusercontent.com/47708807/94646971-e9ad4300-0308-11eb-8b82-9e30faaade4b.png">
**

You used this feature in the previous version of TvMaze ....

For what purpose is this function used, what makes it convenient for us?

When the *Recyclerview* adapter inherits from the *ListAdapter*, the *notifyItem .... (position, Payload)* methods do not work, so does using *ItemCallback*'s 3rd function help? I would be happy if you share your knowledge! Thank you !!!

**Comment by ch8n** [comment]
hi @GulmirzaNorboyev there can be a partial data update for a recycler view holder or a full one, payload enables to send smaller bites of data that has been updated, so instead rebinding the entire view holder with new data you just update the values you have received into your payload, 

read more from here, 
https://stackoverflow.com/questions/41172427/need-an-explanation-why-recyclerview-adapter-notifyitemchangedint-position-obj

**Comment by GulmirzaNorboyev** [comment]
> hi @GulmirzaNorboyev there can be a partial data update for a recycler view holder or a full one, payload enables to send smaller bites of data that has been updated, so instead rebinding the entire view holder with new data you just update the values you have received into your payload,
> 
> read more from here,
> https://stackoverflow.com/questions/41172427/need-an-explanation-why-recyclerview-adapter-notifyitemchangedint-position-obj

Thank you bro! But I know why payload is used, but I couldn't use it in `ListAdapter<Model, VH>(DiffUtil.ItemCallback)`

**Comment by reactivedroid** [comment]
> > hi @GulmirzaNorboyev there can be a partial data update for a recycler view holder or a full one, payload enables to send smaller bites of data that has been updated, so instead rebinding the entire view holder with new data you just update the values you have received into your payload,
> > read more from here,
> > https://stackoverflow.com/questions/41172427/need-an-explanation-why-recyclerview-adapter-notifyitemchangedint-position-obj
> 
> Thank you bro! But I know why payload is used, but I couldn't use it in `ListAdapter<Model, VH>(DiffUtil.ItemCallback)`

You are probably missing on defining the `DiffUtilCallback` properly. Pls note that `getChangePayload` will only be if the `areItemsTheSame` and `areContentsTheSame` return `true`. It basically means that an item viewholder will refresh only some of its contents which have actually changed. For ex: Downloading a movie item will only have download progress update rather than the full item. Hope this makes it more clear
